### ISSUE TITLE
Feature request: allow paying to LNURL

### ISSUE THREAD

**Issue by michael1011** [bordalix/helm-wallet#2]
https://github.com/BoltzExchange/boltz-web-app/blob/7f3791406db4c042cdbe6b5f86528d0b5498423b/src/utils/invoice.ts#L67
Feel free to look at that for reference

**Comment by bordalix** [comment]
Fixed by [cd97da3](https://github.com/bordalix/helm-wallet/commit/cd97da3e58c6c5edf99d07c6c1eb1019384556c2)
