### ISSUE TITLE
Pay lightning invoice without amount from Coinos.io error

### ISSUE THREAD

**Issue by blankscreengithub** [bordalix/helm-wallet#8]
I'm getting a red error at the top of the screen when scanning or pasting an invoice from Coinos.io:

Error decoding invoice

**Comment by bordalix** [comment]
Can you paste the invoice here?
Or decode it with https://lightningdecoder.com/ and see if there are any errors.

**Comment by blankscreengithub** [comment]
I got it to work by specifying the sats amount in the invoice on Coinos.io.

I get the error when I don't specify the amount in the invoice.

Not sure if this is really a bug, but I can pay Coinos invoices that don't have an amount specified with Strike.

Maybe there could be an option to specify the amount in the Helm Wallet when no amount is specified in the invoice?

**Comment by bordalix** [comment]
Interesting.

Do you mind generate an invoice without an amount and paste it here?

Your suggestion is easily doable.

**Comment by bordalix** [comment]
Ahhh, Boltz does not support swaps with invoices without amount, so Helm doesn't to.

You can check by yourself:
- get a coinos.io invoice without amount
- try to swap to Lightning in https://boltz.exchange/
- you'll get the error "Invoices without amount are not supported"

Sorry about that.

**Comment by blankscreengithub** [comment]
Thanks! I kind of figured it was on the boltz side. It's not an issue, but maybe the Helm wallet can pop up with a clearer message that an amount needs to be specified. Grandma is not going to know what "Error decoding invoice" means. ;-)

**Comment by bordalix** [comment]
Eheheh... There's now a specific error message when that occurs:

"Invoices without amount are not supported"

I think grandma is happy 😛 

Thanks for finding this.
