### ISSUE TITLE
Phone camera not scanning invoice

### ISSUE THREAD

**Issue by blankscreengithub** [bordalix/helm-wallet#9]
The window for scanning an invoice is small and it didn't scan the invoice I was trying to pay. Maybe the camera window could be enlarged to help.

Samsung Fold3 using edge 

![Screenshot_20240929_183700_Edge](https://github.com/user-attachments/assets/9e4af1e7-4f92-45d2-9728-d2b89f43898a)

**Comment by bordalix** [comment]
Can you try with a different browser and let me know how it went?

**Comment by blankscreengithub** [comment]
I tried with the Samsung Internet browser and I still get the same small camera window.

**Comment by bordalix** [comment]
But are you able to scan the invoice with it or not?

**Comment by blankscreengithub** [comment]
Either browser will scan an invoice from Coinos.io, but the original post referred to scanning an invoice from The Bitcoin Company and it didn't work. The next time I buy something from the bitcoin company, I'll try the Samsung Internet browser instead

**Comment by bordalix** [comment]
Considering the size, I think it has to do with being a fold phone.
Since I don't have a fold phone, I cannot test it, sorry.

I just tried with a TBC qrcode and it worked, so I'm closing this now.

Feel free to re-open it or open a new one if your problem persists.

**Comment by blankscreengithub** [comment]
FYI this was just using the main camera when the phone was folded.
